/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package creencias;

import javax.swing.JOptionPane;

/**
 *
 * @author LDS
 */
public class nuevoformulario extends javax.swing.JFrame {

    vector a = new vector();
    public nuevoformulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("creencia 1 ");

        jLabel2.setText("creencia 2 ");

        jLabel3.setText("creencia 3");

        jLabel4.setText("creencia 4");

        jLabel5.setText("creencia 5");

        jLabel6.setText("creencia 6");

        jLabel7.setText("creencia 7");

        jLabel8.setText("creencia 8");

        jLabel9.setText("creencia 9");

        jLabel10.setText("creencia 10");

        jLabel11.setText("creencia 11");

        jLabel12.setText("creencia 12");

        jLabel13.setText("creencia 13");

        jLabel14.setText("creencia 14");

        jLabel15.setText("creencia 15");

        jLabel16.setText("creencia 16");

        jLabel17.setText("creencia 17");

        jLabel18.setText("creencia 18");

        jLabel19.setText("creencia 19");

        jLabel20.setText("creencia 20");

        jLabel21.setText("creencia 21");

        jLabel22.setText("creencia 22");

        jLabel23.setText("creencia 23");

        jLabel24.setText("creencia 24");

        jLabel25.setText("creencia 25");

        jLabel26.setText("creencia 26");

        jLabel27.setText("creencia 27");

        jLabel28.setText("creencia 28");

        jButton1.setText("ordenar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("desordenar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("insercion");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel17))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel19))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int i = 0;
    String c; 
    c =  a.ordenar(i);
    jLabel1.setText(c);
    i = 1;
    c = a.ordenar(i); 
    jLabel2.setText(c);
    i = 2;
    c = a.ordenar(i);
    jLabel3.setText(c);
    i = 3; 
    c = a.ordenar(i); 
    jLabel4.setText(c);
    i = 4; 
    c = a.ordenar(i); 
    jLabel5.setText(c);
    i = 5; 
    c = a.ordenar(i); 
    jLabel6.setText(c);
    i = 6; 
    c = a.ordenar(i); 
    jLabel7.setText(c);
    i = 7; 
    c = a.ordenar(i); 
    jLabel8.setText(c);
    i = 8; 
    c = a.ordenar(i); 
    jLabel9.setText(c);
    i = 9; 
    c = a.ordenar(i); 
    jLabel10.setText(c);
    i = 10; 
    c = a.ordenar(i); 
    jLabel11.setText(c);
    i = 11; 
    c = a.ordenar(i); 
    jLabel12.setText(c);
    i = 12; 
    c = a.ordenar(i); 
    jLabel13.setText(c);
    i = 13; 
    c = a.ordenar(i); 
    jLabel14.setText(c);
    i = 14; 
    c = a.ordenar(i); 
    jLabel15.setText(c);
    i = 15; 
    c = a.ordenar(i); 
    jLabel16.setText(c);
    i = 16; 
    c = a.ordenar(i); 
    jLabel17.setText(c);
    i = 17; 
    c = a.ordenar(i); 
    jLabel18.setText(c);
    i = 18; 
    c = a.ordenar(i); 
    jLabel19.setText(c);
    i = 19; 
    c = a.ordenar(i); 
    jLabel20.setText(c);
    i = 20; 
    c = a.ordenar(i); 
    jLabel21.setText(c);
    i = 21; 
    c = a.ordenar(i); 
    jLabel22.setText(c);
    i = 22; 
    c = a.ordenar(i); 
    jLabel23.setText(c);
    i = 23; 
    c = a.ordenar(i); 
    jLabel24.setText(c);
    i = 24; 
    c = a.ordenar(i); 
    jLabel25.setText(c);
    i = 25; 
    c = a.ordenar(i); 
    jLabel26.setText(c);
    i = 26; 
    c = a.ordenar(i); 
    jLabel27.setText(c);
    i = 27; 
    c = a.ordenar(i); 
    jLabel28.setText(c);
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     int i = 0;
    String c; 
    c =  a.desordenar(i);
    jLabel1.setText(c);
    i = 1;
    c = a.desordenar(i); 
    jLabel2.setText(c);
    i = 2;
    c = a.desordenar(i);
    jLabel3.setText(c);
    i = 3; 
    c = a.desordenar(i); 
    jLabel4.setText(c);
    i = 4; 
    c = a.desordenar(i); 
    jLabel5.setText(c);
    i = 5; 
    c = a.desordenar(i); 
    jLabel6.setText(c);
    i = 6; 
    c = a.desordenar(i); 
    jLabel7.setText(c);
    i = 7; 
    c = a.desordenar(i); 
    jLabel8.setText(c);
    i = 8; 
    c = a.desordenar(i); 
    jLabel9.setText(c);
    i = 9; 
    c = a.desordenar(i); 
    jLabel10.setText(c);
    i = 10; 
    c = a.desordenar(i); 
    jLabel11.setText(c);
    i = 11; 
    c = a.desordenar(i); 
    jLabel12.setText(c);
    i = 12; 
    c = a.desordenar(i); 
    jLabel13.setText(c);
    i = 13; 
    c = a.desordenar(i); 
    jLabel14.setText(c);
    i = 14; 
    c = a.desordenar(i); 
    jLabel15.setText(c);
    i = 15; 
    c = a.desordenar(i); 
    jLabel16.setText(c);
    i = 16; 
    c = a.desordenar(i); 
    jLabel17.setText(c);
    i = 17; 
    c = a.desordenar(i); 
    jLabel18.setText(c);
    i = 18; 
    c = a.desordenar(i); 
    jLabel19.setText(c);
    i = 19; 
    c = a.desordenar(i); 
    jLabel20.setText(c);
    i = 20; 
    c = a.desordenar(i); 
    jLabel21.setText(c);
    i = 21; 
    c = a.desordenar(i); 
    jLabel22.setText(c);
    i = 22; 
    c = a.desordenar(i); 
    jLabel23.setText(c);
    i = 23; 
    c = a.desordenar(i); 
    jLabel24.setText(c);
    i = 24; 
    c = a.desordenar(i); 
    jLabel25.setText(c);
    i = 25; 
    c = a.desordenar(i); 
    jLabel26.setText(c);
    i = 26; 
    c = a.desordenar(i); 
    jLabel27.setText(c);
    i = 27; 
    c = a.desordenar(i); 
    jLabel28.setText(c);
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int i = 0;
    String c; 
    c =  a.insercion(i);
    jLabel1.setText(c);
    i = 1;
    c = a.insercion(i); 
    jLabel2.setText(c);
    i = 2;
    c = a.insercion(i);
    jLabel3.setText(c);
    i = 3; 
    c = a.insercion(i); 
    jLabel4.setText(c);
    i = 4; 
    c = a.insercion(i); 
    jLabel5.setText(c);
    i = 5; 
    c = a.insercion(i); 
    jLabel6.setText(c);
    i = 6; 
    c = a.insercion(i); 
    jLabel7.setText(c);
    i = 7; 
    c = a.insercion(i); 
    jLabel8.setText(c);
    i = 8; 
    c = a.insercion(i); 
    jLabel9.setText(c);
    i = 9; 
    c = a.insercion(i); 
    jLabel10.setText(c);
    i = 10; 
    c = a.insercion(i); 
    jLabel11.setText(c);
    i = 11; 
    c = a.insercion(i); 
    jLabel12.setText(c);
    i = 12; 
    c = a.insercion(i); 
    jLabel13.setText(c);
    i = 13; 
    c = a.insercion(i); 
    jLabel14.setText(c);
    i = 14; 
    c = a.insercion(i); 
    jLabel15.setText(c);
    i = 15; 
    c = a.insercion(i); 
    jLabel16.setText(c);
    i = 16; 
    c = a.insercion(i); 
    jLabel17.setText(c);
    i = 17; 
    c = a.insercion(i); 
    jLabel18.setText(c);
    i = 18; 
    c = a.insercion(i); 
    jLabel19.setText(c);
    i = 19; 
    c = a.insercion(i); 
    jLabel20.setText(c);
    i = 20; 
    c = a.insercion(i); 
    jLabel21.setText(c);
    i = 21; 
    c = a.insercion(i); 
    jLabel22.setText(c);
    i = 22; 
    c = a.insercion(i); 
    jLabel23.setText(c);
    i = 23; 
    c = a.insercion(i); 
    jLabel24.setText(c);
    i = 24; 
    c = a.insercion(i); 
    jLabel25.setText(c);
    i = 25; 
    c = a.insercion(i); 
    jLabel26.setText(c);
    i = 26; 
    c = a.insercion(i); 
    jLabel27.setText(c);
    i = 27; 
    c = a.insercion(i); 
    jLabel28.setText(c);
    
                           
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       try{
        int bus = Integer.parseInt(jTextField1.getText()); 
        jLabel29.setText(a.busqueda(bus));
       }
       catch(Exception errordato)
       {
           JOptionPane.showInternalMessageDialog(null, "error de dato", "ERROR", WIDTH);
       }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuevoformulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuevoformulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuevoformulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuevoformulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nuevoformulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
